version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_HOST=vectordb
      - CHROMA_PORT=8002
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    depends_on:
      - vectordb
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8800:8501"
    environment:
      - BACKEND_URL=http://backend:8002
    depends_on:
      - backend
    networks:
      - rag-network

  vectordb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  chroma_data: